# Generated by Django 3.1.7 on 2021-03-21 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_participantrole'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activities.activitytype')),
                ('participant_role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='activities.participantrole')),
            ],
        ),
    ]
